/* Generated by Yosys 0.36+42 (git sha1 70d35314d, clang 11.0.1-2 -fPIC -Os) */

module classic_squarer ( 
	`ifdef USE_POWER_PINS
		inout vccd2,	// User area 2 1.8v supply
		inout vssd2,	// User area 2 digital ground
	`endif
  	input 	[162:0] a,
  	output 	[162:0] c);


  poly_reducer inst_reduc ( 
		 `ifdef USE_POWER_PINS
			.vccd2(vccd2),	// User area 2 1.8v supply
			.vssd2(vssd2),	// User area 2 digital ground
		`endif
		
		.d({a[162], 1'b0, a[161], 1'b0, a[160], 1'b0, 
        a[159], 1'b0, a[158], 1'b0, a[157], 1'b0, a[156], 1'b0, a[155], 1'b0, 
        a[154], 1'b0, a[153], 1'b0, a[152], 1'b0, a[151], 1'b0, a[150], 1'b0, 
        a[149], 1'b0, a[148], 1'b0, a[147], 1'b0, a[146], 1'b0, a[145], 1'b0, 
        a[144], 1'b0, a[143], 1'b0, a[142], 1'b0, a[141], 1'b0, a[140], 1'b0, 
        a[139], 1'b0, a[138], 1'b0, a[137], 1'b0, a[136], 1'b0, a[135], 1'b0, 
        a[134], 1'b0, a[133], 1'b0, a[132], 1'b0, a[131], 1'b0, a[130], 1'b0, 
        a[129], 1'b0, a[128], 1'b0, a[127], 1'b0, a[126], 1'b0, a[125], 1'b0, 
        a[124], 1'b0, a[123], 1'b0, a[122], 1'b0, a[121], 1'b0, a[120], 1'b0, 
        a[119], 1'b0, a[118], 1'b0, a[117], 1'b0, a[116], 1'b0, a[115], 1'b0, 
        a[114], 1'b0, a[113], 1'b0, a[112], 1'b0, a[111], 1'b0, a[110], 1'b0, 
        a[109], 1'b0, a[108], 1'b0, a[107], 1'b0, a[106], 1'b0, a[105], 1'b0, 
        a[104], 1'b0, a[103], 1'b0, a[102], 1'b0, a[101], 1'b0, a[100], 1'b0, 
        a[99], 1'b0, a[98], 1'b0, a[97], 1'b0, a[96], 1'b0, a[95], 1'b0, a[94], 
        1'b0, a[93], 1'b0, a[92], 1'b0, a[91], 1'b0, a[90], 1'b0, a[89], 1'b0, 
        a[88], 1'b0, a[87], 1'b0, a[86], 1'b0, a[85], 1'b0, a[84], 1'b0, a[83], 
        1'b0, a[82], 1'b0, a[81], 1'b0, a[80], 1'b0, a[79], 1'b0, a[78], 1'b0, 
        a[77], 1'b0, a[76], 1'b0, a[75], 1'b0, a[74], 1'b0, a[73], 1'b0, a[72], 
        1'b0, a[71], 1'b0, a[70], 1'b0, a[69], 1'b0, a[68], 1'b0, a[67], 1'b0, 
        a[66], 1'b0, a[65], 1'b0, a[64], 1'b0, a[63], 1'b0, a[62], 1'b0, a[61], 
        1'b0, a[60], 1'b0, a[59], 1'b0, a[58], 1'b0, a[57], 1'b0, a[56], 1'b0, 
        a[55], 1'b0, a[54], 1'b0, a[53], 1'b0, a[52], 1'b0, a[51], 1'b0, a[50], 
        1'b0, a[49], 1'b0, a[48], 1'b0, a[47], 1'b0, a[46], 1'b0, a[45], 1'b0, 
        a[44], 1'b0, a[43], 1'b0, a[42], 1'b0, a[41], 1'b0, a[40], 1'b0, a[39], 
        1'b0, a[38], 1'b0, a[37], 1'b0, a[36], 1'b0, a[35], 1'b0, a[34], 1'b0, 
        a[33], 1'b0, a[32], 1'b0, a[31], 1'b0, a[30], 1'b0, a[29], 1'b0, a[28], 
        1'b0, a[27], 1'b0, a[26], 1'b0, a[25], 1'b0, a[24], 1'b0, a[23], 1'b0, 
        a[22], 1'b0, a[21], 1'b0, a[20], 1'b0, a[19], 1'b0, a[18], 1'b0, a[17], 
        1'b0, a[16], 1'b0, a[15], 1'b0, a[14], 1'b0, a[13], 1'b0, a[12], 1'b0, 
        a[11], 1'b0, a[10], 1'b0, a[9], 1'b0, a[8], 1'b0, a[7], 1'b0, a[6], 
        1'b0, a[5], 1'b0, a[4], 1'b0, a[3], 1'b0, a[2], 1'b0, a[1], 1'b0, a[0]}), .c(c) );
endmodule

module poly_reducer (
	`ifdef USE_POWER_PINS
		inout vccd2,	// User area 2 1.8v supply
		inout vssd2,	// User area 2 digital ground
	`endif
	input [324:0] d,
  	output [162:0] c);
  	
	wire   	n7, n13, n15, n18, n25, n30, n33, n35, n38, n39, n40, n45, n50, n53,
         	n54, n55, n60, n63, n70, n73, n74, n77, n80, n85, n88, n89, n90, n91,
			n97, n102, n105, n106, n109, n112, n117, n119, n120, n123, n124, n127,
			n130, n135, n138, n140, n146, n149, n155, n158, n160, n166, n170,
			n175, n177, n178, n183, n185, n188, n191, n194, n199, n202, n203,
			n206, n209, n214, n217, n218, n221, n224, n229, n234, n235, n238,
			n241, n243, n258, n262, n263, n270, n275, n279, n280, n281, n286,
			n288, n293, n298, n301, n302, n305, n308, n315, n318, n319, n322,
			n324, n330, n333, n336, n343, n346, n347, n348, n353, n358, n361,
			n362, n363, n370, n375, n378, n379, n380, n385, n390, n392, n393,
			n397, n398, n404, n409, n417, n418, n4, n5, n6, n8, n11;

	assign c[99] 	= 	~(d[256] ^ n7);
	assign c[97] 	= 	~(d[254] ^ n13);
	assign c[96] 	= 	~(n15 ^ n18);
	assign n15 		= 	d[96] ^ d[256];
	assign c[95] 	= 	~(d[258] ^ n18);
	assign c[92] 	= 	~(d[92] ^ n25);
	assign n25 		= 	~(d[248] ^ d[252]);
	assign c[90] 	= 	~(n30 ^ n38);
	assign n30 		= 	d[90] ^ d[250];
	assign c[8] 	= 	d[168] ^ n33;
	assign n33 		= 	~(d[8] ^ n35);
	assign n35 		= 	~(d[322] ^ n149);
	assign c[89] 	= 	~(d[252] ^ n38);
	assign c[88] 	= 	~(n39 ^ n40);
	assign n39 		= 	d[88] ^ d[248];
	assign c[87] 	= 	~(d[250] ^ n40);
	assign c[86] 	=	~(d[86] ^ n45);
	assign n45 		= 	~(d[242] ^ d[246]);
	assign c[84] 	= 	~(n50 ^ n53);
	assign n50 		= 	d[84] ^ d[244];
	assign c[83] 	= 	~(d[246] ^ n53);
	assign c[82] 	= 	~(n54 ^ n55);
	assign n54 		= 	d[82] ^ d[242];
	assign c[81]	=	~(n55	^	d[244]);
	assign c[80]	=	~(n60	^	d[80]);
	assign n60		=	~(d[240]	^	d[236]);
	assign c[7]		=	~(n63	^	d[164]);
	assign c[78]	=	~(n73	^	n70);
	assign n70		=		d[238]	^	d[78];
	assign c[77]	=	~(	n73	^	d[240]);
	assign c[76]	=	~(	n77	^	n74);
	assign n74		=		d[236]	^	d[76];
	assign c[75]	=	~(	n77	^	d[238]);
	assign c[74]	=	~(	n80	^	d[74]);
	assign n80		=	~(	d[234]	^	d[230]);
	assign c[72]	=	~(	n88	^	n85);
	assign n85		=		d[232]	^	d[72];
	assign c[71]	=	~(	n88	^	d[234]);
	assign c[70]	=	~(	n90	^	n89);
	assign n89		=		d[230]	^	d[70];
	assign c[6]		=	~(	d[6]	^	n91);
	assign c[69]	=	~(	n90	^	d[232]);
	assign c[68]	=	~(	n97	^	d[68]);
	assign n97		=	~(	d[228]	^	d[224]);
	assign c[66]	=	~(	n105	^	n102);
	assign n102		=		d[226]	^	d[66];
	assign c[65]	=	~(	n105	^	d[228]);
	assign c[64]	=	~(	n109	^	n106);
	assign n106		=		d[224]	^	d[64];
	assign c[63]	=	~(	n109	^	d[226]);
	assign c[62]	=	~(	n112	^	d[62]);
	assign n112		=	~(	d[222]	^	d[218]);
	assign c[60]	=	~(	n123	^	n117);
	assign n117		=		d[220]	^	d[60];
	assign c[5]		=	~(	n120	^	n119);
	assign c[59]	=	~(	n123	^	d[222]);
	assign c[58]	=	~(	n127	^	n124);
	assign n124		=		d[218]	^	d[58];
	assign c[57]	=	~(	n127	^	d[220]);
	assign c[56]	=	~(	n130	^	d[56]);
	assign n130		=	~(	d[216]	^	d[212]);
	assign c[54]	=	~(	n138	^	n135);
	assign n135		=		d[214]	^	d[54];
	assign c[53]	=	~(	n138	^	d[216]);
	assign c[52]	=	~(	n140	^	d[52]);
	assign n140		=	~(	d[212]	^	d[208]);
	assign c[50]	=	~(	n146	^	d[50]);
	assign n146		=	~(	d[210]	^	d[206]);
	assign c[48]	=	~(	n158	^	n155);
	assign n155		=		d[208]	^	d[48];
	assign c[47]	=	~(	n158	^	d[210]);
	assign c[46]	=	~(	n160	^	d[46]);
	assign n160		=	~(	d[206]	^	d[202]);
	assign c[44]	=	~(	n166	^	d[44]);
	assign n166		=	~(	d[204]	^	d[200]);
	assign c[42]	=	~(	n185	^	n170);
	assign n170		=		d[202]	^	d[42];
	assign c[41]	=	~(	n185	^	d[204]);
	assign c[40]	=	~(	n175	^	d[40]);
	assign n175		=	~(	d[200]	^	d[196]);
	assign n91		=	~(	n178	^	n177);
	assign n177		=	~(	d[322]	^	d[166]);
	assign c[38]	=		n183	^	d[194];
	assign n183		=	~(	n185	^	d[38]);
	assign c[36]	=	~(	n191	^	n188);
	assign n188		=		d[196]	^	d[36];
	assign c[35]	=	~(	n191	^	d[198]);
	assign c[34]	=	~(	n194	^	d[34]);
	assign n194		=	~(	d[194]	^	d[190]);
	assign c[32]	=	~(	n202	^	n199);
	assign n199		=		d[192]	^	d[32];
	assign c[31]	=	~(	n202	^	d[194]);
	assign c[30]	=	~(	n206	^	n203);
	assign n203		=		d[190]	^	d[30];
	assign c[2]		=	~(	n119	^	d[2]);
	assign c[29]	=	~(	n206	^	d[192]);
	assign c[28]	=	~(	n209	^	d[28]);
	assign n209		=	~(	d[188]	^	d[184]);
	assign c[26]	=	~(	n217	^	n214);
	assign n214		=		d[186]	^	d[26];
	assign c[25]	=	~(	n217	^	d[188]);
	assign c[24]	=	~(	n221	^	n218);
	assign n218		=		d[184]	^	d[24];
	assign c[23]	=	~(	n221	^	d[186]);
	assign c[22]	=	~(	n224	^	d[22]);
	assign n224		=	~(	d[182]	^	d[178]);
	assign c[20]	=	~(	n234	^	n229);
	assign n229		=		d[180]	^	d[20];
	assign c[19]	=	~(	n234	^	d[182]);
	assign c[18]	=	~(	n238	^	n235);
	assign n235		=		d[178]	^	d[18];
	assign c[17]	=	~(	n238	^	d[180]);
	assign c[16]	=	~(	n241	^	d[16]);
	assign n241		=	~(	d[176]	^	d[172]);
	assign c[162]	=	~(	n243	^	d[162]);
	assign c[159]	=	~(	n119	^	d[316]);
	assign c[158]	=	~(	n262	^	n258);
	assign n258		=		d[158]	^	d[318];
	assign c[157]	=	~(	n262	^	d[320]);
	assign c[156]	=		n263	^	d[312];
	assign n263		=		d[316]	^	d[156];
	assign c[154]	=	~(	n270	^	d[154]);
	assign n270		=	~(	d[314]	^	d[310]);
	assign c[152]	=	~(	n288	^	n275);
	assign n275		=		d[312]	^	d[152];
	assign c[151]	=	~(	n288	^	d[314]);
	assign c[150]	=	~(	n280	^	n279);
	assign n279		=		d[310]	^	d[150];
	assign c[14]	=	~(	n63	^	n281);
	assign n281		=		d[174]	^	d[14];
	assign c[149]	=	~(	n280	^	d[312]);
	assign c[148]	=		n286	^	d[304];
	assign n286		=	~(	n288	^	d[148]);
	assign c[146]	=	~(	n293	^	d[146]);
	assign n293		=	~(	d[306]	^	d[302]);
	assign c[144]	=	~(	n301	^	n298);
	assign n298		=		d[304]	^	d[144];
	assign c[143]	=	~(	n301	^	d[306]);
	assign c[142]	=	~(	n305	^	n302);
	assign n302		=		d[302]	^	d[142];
	assign c[141]	=	~(	n305	^	d[304]);
	assign c[140]	=	~(	n308	^	d[140]);
	assign n308			=	~(	d[300]	^	d[296]);
	assign c[13]	=	~(	n63	^	d[176]);
	assign c[138]	=	~(	n318	^	n315);
	assign n315		=		d[298]	^	d[138];
	assign c[137]	=	~(	n318	^	d[300]);
	assign c[136]	=	~(	n322	^	n319);
	assign n319		=		d[296]	^	d[136];
	assign c[135]	=	~(	n322	^	d[298]);
	assign c[134]	=		n324	^	d[290];
	assign n324		=	~(	n318	^	d[134]);
	assign c[132]	=	~(	n333	^	n330);
	assign n330		=		d[292]	^	d[132];
	assign c[131]	=	~(	n333	^	d[294]);
	assign c[130]	=	~(	n336	^	d[130]);
	assign n336		=	~(	d[290]	^	d[286]);
	assign n120		=		d[168]	^	d[324];
	assign c[128]	=	~(	n346	^	n343);
	assign n343		=		d[288]	^	d[128];
	assign c[127]	=	~(	n346	^	d[290]);
	assign c[126]	=	~(	n348	^	n347);
	assign n347		=		d[286]	^	d[126];
	assign c[125]	=	~(	n348	^	d[288]);
	assign c[124]	=	~(	n353	^	d[124]);
	assign n353		=	~(	d[284]	^	d[280]);
	assign c[122]	=	~(	n361	^	n358);
	assign n358		=		d[282]	^	d[122];
	assign c[121]	=	~(	n361	^	d[284]);
	assign c[120]	=	~(	n363	^	n362);
	assign n362		=		d[280]	^	d[120];
	assign c[119]	=	~(	n363	^	d[282]);
	assign c[118]	=	~(	n370	^	d[118]);
	assign n370		=	~(	d[278]	^	d[274]);
	assign c[116]	=	~(	n378	^	n375);
	assign n375		=		d[276]	^	d[116];
	assign c[115]	=	~(	n378	^	d[278]);
	assign c[114]	=	~(	n380	^	n379);
	assign n379		=		d[274]	^	d[114];
	assign c[113]	=	~(	n380	^	d[276]);
	assign c[112]	=	~(	n385	^	d[112]);
	assign n385		=	~(	d[272]	^	d[268]);
	assign c[110]	=	~(	n397	^	n390);
	assign n390		=		d[270]	^	d[110];
	assign c[10]	=	~(	n393	^	n392);
	assign n393		=	~(	n177	^	d[324]);
	assign n392		=	~(	d[10]	^	d[170]);
	assign c[109]	=	~(	n397	^	d[272]);
	assign c[108]	=	~(	n417	^	n398);
	assign n398		=		d[268]	^	d[108];
	assign c[107]	=	~(	n417	^	d[270]);
	assign c[106]	=	~(	n404	^	d[106]);
	assign n404		=	~(	d[266]	^	d[262]);
	assign c[105]	=	~(	n7	^	d[268]);
	assign c[104]	=	~(	n13	^	n409);
	assign n409		=		d[264]	^	d[104];
	assign c[103]	=	~(	n13	^	d[266]);
	assign c[101]	=	~(	n417	^	d[258]);
	assign c[100]	=		n418	^	d[260];
	assign c[1]		=		n149	^	d[324];
	assign c[4]		=		n149	^	d[4];
	assign n149		=		d[164]	^	d[320];
	assign c[102]	=	~(	n4	^	d[258]);
	assign n4		=	~(	d[262]	^	d[102]);
	assign c[94]	=	~(	n5	^	d[250]);
	assign n5		=	~(	d[254]	^	d[94]);
	assign c[160]	=	~(	n6	^	d[316]);
	assign n6		=	~(	d[320]	^	d[160]);
	assign c[98]	=	~(	n8	^	d[254]);
	assign n8		=	~(	d[258]	^	d[98]);
	assign c[12]	=	~(	n11	^	n120);
	assign n11		=	~(	d[172]	^	d[12]);
	assign c[0]		=	~(	n178	^	d[0]);
	assign n178 	= ~		d[320];
	assign c[145]	=		d[302]	^	d[308];
	assign c[129]	=		d[286]	^	d[292];
	assign c[51]	=		d[208]	^	d[214];
	assign c[11]	=		d[168]	^	d[174];
	assign c[9]		=		d[166]	^	d[172];
	assign c[117]	=		d[274]	^	d[280];
	assign c[123]	=		d[280]	^	d[286];
	assign c[139]	=		d[296]	^	d[302];
	assign c[147]	=		d[304]	^	d[310];
	assign c[153]	=		d[310]	^	d[316];
	assign c[15]	=		d[172]	^	d[178];
	assign c[21]	=		d[178]	^	d[184];
	assign c[27]	=		d[184]	^	d[190];
	assign c[33]	=		d[190]	^	d[196];
	assign c[39]	=		d[196]	^	d[202];
	assign c[45]	=		d[202]	^	d[208];
	assign c[61]	=		d[218]	^	d[224];
	assign c[67]	=		d[224]	^	d[230];
	assign c[73]	=		d[230]	^	d[236];
	assign c[79]	=		d[236]	^	d[242];
	assign c[85]	=		d[242]	^	d[248];
	assign c[91]	=		d[248]	^	d[254];
	assign c[93]	=		d[256]	^	d[250];
	assign c[111]	=		d[268]	^	d[274];
	assign c[133]	=		d[290]	^	d[296];
	assign c[55]	=		d[212]	^	d[218];
	assign c[37]	=		d[194]	^	d[200];
	assign c[43]	=		d[200]	^	d[206];
	assign c[49]	=		d[206]	^	d[212];
	assign c[155]	=		d[312]	^	d[318];
	assign c[161]	=		d[324]	^	d[318];
	assign n243		=	~(d[318]	^	d[322]);
	assign n418		=	d[100]		^	d[256];
	assign c[3] 	= 	~n91;			
	assign n417		=	~d[264];			
	assign n238		=	~d[174];			
	assign n234		=	~d[176];			
	assign n221		=	~d[180];			
	assign n217		=	~d[182];			
	assign n206		=	~d[186];			
	assign n202		=	~d[188];			
	assign n191		=	~d[192];			
	assign n185		=	~d[198];			
	assign n158		=	~d[204];			
	assign n138		=	~d[210];			
	assign n127		=	~d[214];			
	assign n123		=	~d[216];			
	assign n109		=	~d[220];			
	assign n105		=	~d[222];			
	assign n90		=	~d[226];			
	assign n88		=	~d[228];			
	assign n77		=	~d[232];			
	assign n73		=	~d[234];			
	assign n55		=	~d[238];			
	assign n53		=	~d[240];			
	assign n40		=	~d[244];			
	assign n38		=	~d[246];			
	assign n18		=	~d[252];			
	assign n13		=	~d[260];			
	assign n7		=	~d[262];		
	assign n397		=	~d[266];			
	assign n380		=	~d[270];			
	assign n378		=	~d[272];			
	assign n363		=	~d[276];			
	assign n361		=	~d[278];			
	assign n348		=	~d[282];			
	assign n346		=	~d[284];			
	assign n333		=	~d[288];			
	assign n322		=	~d[292];			
	assign n318		=	~d[294];			
	assign n305		=	~d[298];			
	assign n301		=	~d[300];			
	assign n288		=	~d[308];			
	assign n280		=	~d[306];			
	assign n262		=	~d[314];			
	assign n63		=	~d[170];			
	assign n119		=	~d[322];			

endmodule
